In [1]:
import warnings
warnings.filterwarnings('ignore')

In [2]:
from plaid import Client

In [3]:
client = Client(client_id='5ecb6e9083a47600129f6c96', 
                secret='1e57db1ee4b1d67ccd22bf251c7ca9', 
                public_key='7927b0917e8bb6d8f48eff2c76b85a', 
                environment='sandbox')
access_token = 'access-sandbox-d81f9298-cdc7-49de-8ed2-3fdd1673e961' 

response = client.Transactions.get(access_token, start_date='2010-01-01', end_date='2020-05-25')
transactions = response['transactions']

# the transactions in the response are paginated, so make multiple calls while increasing the offset to
# retrieve all transactions
while len(transactions) < response['total_transactions']:
    response = client.Transactions.get(access_token, start_date='2010-01-01', end_date='2020-05-25',
                                       offset=len(transactions)
                                      )
    transactions.extend(response['transactions'])

In [5]:
len(transactions)

390

In [4]:
transactions[0]

{'account_id': 'lVKvzlNw69cW9j9NRDrkswg1obbBK5HZ8KJvW',
 'account_owner': None,
 'amount': 500,
 'authorized_date': None,
 'category': ['Food and Drink', 'Restaurants'],
 'category_id': '13005000',
 'date': '2020-05-25',
 'iso_currency_code': 'USD',
 'location': {'address': None,
  'city': None,
  'country': None,
  'lat': None,
  'lon': None,
  'postal_code': None,
  'region': None,
  'store_number': None},
 'name': 'Tectra Inc',
 'payment_channel': 'in store',
 'payment_meta': {'by_order_of': None,
  'payee': None,
  'payer': None,
  'payment_method': None,
  'payment_processor': None,
  'ppd_id': None,
  'reason': None,
  'reference_number': None},
 'pending': False,
 'pending_transaction_id': None,
 'transaction_code': None,
 'transaction_id': 'gV5nL83RoPcRwLwgdN8DH9wmv5avVEHg1oM7x',
 'transaction_type': 'place',
 'unofficial_currency_code': None}

In [6]:
import pandas as pd
df = pd.DataFrame(transactions)

In [7]:
df.head(3)

,account_id,account_owner,amount,authorized_date,category,category_id,date,iso_currency_code,location,name,payment_channel,payment_meta,pending,pending_transaction_id,transaction_code,transaction_id,transaction_type,unofficial_currency_code
0,lVKvzlNw69cW9j9NRDrkswg1obbBK5HZ8KJvW,None,500.0,None,"[Food and Drink, Restaurants]",13005000,2020-05-25,USD,"{'address': None, 'city': None, 'country': Non...",Tectra Inc,in store,"{'by_order_of': None, 'payee': None, 'payer': ...",False,None,None,gV5nL83RoPcRwLwgdN8DH9wmv5avVEHg1oM7x,place,None
1,lVKvzlNw69cW9j9NRDrkswg1obbBK5HZ8KJvW,None,2078.5,None,[Payment],16000000,2020-05-24,USD,"{'address': None, 'city': None, 'country': Non...",AUTOMATIC PAYMENT - THANK,other,"{'by_order_of': None, 'payee': None, 'payer': ...",False,None,None,WG5jed913Lt1d4d3b6MKIVR178x7BDtlER4Qr,special,None
2,lVKvzlNw69cW9j9NRDrkswg1obbBK5HZ8KJvW,None,500.0,None,"[Food and Drink, Restaurants, Fast Food]",13005032,2020-05-24,USD,"{'address': None, 'city': None, 'country': Non...",KFC,in store,"{'by_order_of': None, 'payee': None, 'payer': ...",False,None,None,E45mg16qJwFqjejpLG4wUmXq1o31yVFXlyE5K,place,None

In [8]:
# колонку 'category' разделим на три части, т.к. в этой колонке находятся списки по 1, 2 или 3 элемента
df['category_1'] = 0
df['category_2'] = 0
df['category_3'] = 0

In [9]:
for i in range(len(df)):
    df['category_1'][i] = df['category'][i][0] 
    
for i in range(len(df)):
    if len(df['category'][i]) > 1:
        df['category_2'][i] = df['category'][i][1] 
        
for i in range(len(df)):
    if len(df['category'][i]) > 2:
        df['category_3'][i] = df['category'][i][2]

In [10]:
df.head(3)

,account_id,account_owner,amount,authorized_date,category,category_id,date,iso_currency_code,location,name,...,payment_meta,pending,pending_transaction_id,transaction_code,transaction_id,transaction_type,unofficial_currency_code,category_1,category_2,category_3
0,lVKvzlNw69cW9j9NRDrkswg1obbBK5HZ8KJvW,None,500.0,None,"[Food and Drink, Restaurants]",13005000,2020-05-25,USD,"{'address': None, 'city': None, 'country': Non...",Tectra Inc,...,"{'by_order_of': None, 'payee': None, 'payer': ...",False,None,None,gV5nL83RoPcRwLwgdN8DH9wmv5avVEHg1oM7x,place,None,Food and Drink,Restaurants,0
1,lVKvzlNw69cW9j9NRDrkswg1obbBK5HZ8KJvW,None,2078.5,None,[Payment],16000000,2020-05-24,USD,"{'address': None, 'city': None, 'country': Non...",AUTOMATIC PAYMENT - THANK,...,"{'by_order_of': None, 'payee': None, 'payer': ...",False,None,None,WG5jed913Lt1d4d3b6MKIVR178x7BDtlER4Qr,special,None,Payment,0,0
2,lVKvzlNw69cW9j9NRDrkswg1obbBK5HZ8KJvW,None,500.0,None,"[Food and Drink, Restaurants, Fast Food]",13005032,2020-05-24,USD,"{'address': None, 'city': None, 'country': Non...",KFC,...,"{'by_order_of': None, 'payee': None, 'payer': ...",False,None,None,E45mg16qJwFqjejpLG4wUmXq1o31yVFXlyE5K,place,None,Food and Drink,Restaurants,Fast Food

In [13]:
# колонки, в которой не находится полезной информации, удалим
# 'category' разделена на три колонки, поэтому основную колонку можно удалить
# 'location' и 'payment_meta' 99% значения в ячейках - None
df_1 = df.drop(['category', 'location', 'payment_meta'], axis=1)

In [14]:
df_1.head(2)

,account_id,account_owner,amount,authorized_date,category_id,date,iso_currency_code,name,payment_channel,pending,pending_transaction_id,transaction_code,transaction_id,transaction_type,unofficial_currency_code,category_1,category_2,category_3
0,lVKvzlNw69cW9j9NRDrkswg1obbBK5HZ8KJvW,None,500.0,None,13005000,2020-05-25,USD,Tectra Inc,in store,False,None,None,gV5nL83RoPcRwLwgdN8DH9wmv5avVEHg1oM7x,place,None,Food and Drink,Restaurants,0
1,lVKvzlNw69cW9j9NRDrkswg1obbBK5HZ8KJvW,None,2078.5,None,16000000,2020-05-24,USD,AUTOMATIC PAYMENT - THANK,other,False,None,None,WG5jed913Lt1d4d3b6MKIVR178x7BDtlER4Qr,special,None,Payment,0,0

In [15]:
# библиотека для работы с google spreadsheets
import gspread
from google.oauth2.service_account import Credentials

In [16]:
# настроим google API
scopes = [
    'https://www.googleapis.com/auth/spreadsheets',
    'https://www.googleapis.com/auth/drive'
]

credentials = Credentials.from_service_account_file(
    '/home/dddiiirrr3/tribal-artifact-278407-89bdd40797a4.json',
    scopes=scopes
)

gc = gspread.authorize(credentials)

In [17]:
# создадим spreadsheets для сырых данных
sh = gc.create('raw_data')

In [18]:
# предоставим доступ
sh.share('dddiiirrr3@gmail.com', perm_type='user', role='writer')

In [19]:
# запишем данные в spreadsheets
list_1 = sh.sheet1
list_1.update([df_1.columns.values.tolist()] + df_1.values.tolist())

{'spreadsheetId': '1vinMyzX5R2JkGjRXyp5pyKpWZYGFidkRlTugd6yChLQ',
 'updatedRange': 'Sheet1!A1:R391',
 'updatedRows': 391,
 'updatedColumns': 18,
 'updatedCells': 5088}

In [62]:
pd.set_option('max_columns', None)   # show all columns
pd.set_option('max_rows', None)      # show all row

In [20]:
# если судить по примеры из скриншота, то большая часть колонок не используется, поэтому удалим ненужное
df_1.head(3)

,account_id,account_owner,amount,authorized_date,category_id,date,iso_currency_code,name,payment_channel,pending,pending_transaction_id,transaction_code,transaction_id,transaction_type,unofficial_currency_code,category_1,category_2,category_3
0,lVKvzlNw69cW9j9NRDrkswg1obbBK5HZ8KJvW,None,500.0,None,13005000,2020-05-25,USD,Tectra Inc,in store,False,None,None,gV5nL83RoPcRwLwgdN8DH9wmv5avVEHg1oM7x,place,None,Food and Drink,Restaurants,0
1,lVKvzlNw69cW9j9NRDrkswg1obbBK5HZ8KJvW,None,2078.5,None,16000000,2020-05-24,USD,AUTOMATIC PAYMENT - THANK,other,False,None,None,WG5jed913Lt1d4d3b6MKIVR178x7BDtlER4Qr,special,None,Payment,0,0
2,lVKvzlNw69cW9j9NRDrkswg1obbBK5HZ8KJvW,None,500.0,None,13005032,2020-05-24,USD,KFC,in store,False,None,None,E45mg16qJwFqjejpLG4wUmXq1o31yVFXlyE5K,place,None,Food and Drink,Restaurants,Fast Food

In [21]:
df_2 = df_1.drop(['account_owner', 'authorized_date', 'category_id', 'iso_currency_code', 
                  'payment_channel', 'pending', 'pending_transaction_id', 'transaction_code', 
                  'transaction_type', 'unofficial_currency_code'], axis=1)

In [22]:
df_2

,account_id,amount,date,name,transaction_id,category_1,category_2,category_3
0,lVKvzlNw69cW9j9NRDrkswg1obbBK5HZ8KJvW,500.0,2020-05-25,Tectra Inc,gV5nL83RoPcRwLwgdN8DH9wmv5avVEHg1oM7x,Food and Drink,Restaurants,0
1,lVKvzlNw69cW9j9NRDrkswg1obbBK5HZ8KJvW,2078.5,2020-05-24,AUTOMATIC PAYMENT - THANK,WG5jed913Lt1d4d3b6MKIVR178x7BDtlER4Qr,Payment,0,0
2,lVKvzlNw69cW9j9NRDrkswg1obbBK5HZ8KJvW,500.0,2020-05-24,KFC,E45mg16qJwFqjejpLG4wUmXq1o31yVFXlyE5K,Food and Drink,Restaurants,Fast Food
3,lVKvzlNw69cW9j9NRDrkswg1obbBK5HZ8KJvW,500.0,2020-05-24,Madison Bicycle Shop,8GkM83QngDtWl6laMrPyskav9z79dliwmnrJy,Shops,Sporting Goods,0
4,Je5lK8m3J4F3MpMQ1lbgUZl3yWWkbjfdqlZLy,25.0,2020-05-15,CREDIT CARD 3333 PAYMENT *//,LZ5KzW9dJ4CdLWLvwKjpFAXdG6wGk9fPa79WK,Payment,Credit Card,0
...,...,...,...,...,...,...,...,...
385,lVKvzlNw69cW9j9NRDrkswg1obbBK5HZ8KJvW,2078.5,2018-06-04,AUTOMATIC PAYMENT - THANK,pV3KdzervPcPRyRN4kLBIrja4vD7V6tLnwKdo,Payment,0,0
386,lVKvzlNw69cW9j9NRDrkswg1obbBK5HZ8KJvW,500.0,2018-06-04,KFC,LZ5KzW9dJ4CdLWLvwKjpFAXjL3qvK1UPa795K,Food and Drink,Restaurants,Fast Food
387,lVKvzlNw69cW9j9NRDrkswg1obbBK5HZ8KJvW,500.0,2018-06-04,Madison Bicycle Shop,1p1NDGaoQ4iaQyQnvoWjHm8ZNlzKWxF5ozm19,Shops,Sporting Goods,0
388,Je5lK8m3J4F3MpMQ1lbgUZl3yWWkbjfdqlZLy,25.0,2018-05-26,CREDIT CARD 3333 PAYMENT *//,Xn57Da9LxgFLmpmqP73EfPD3xMEGZ8tdEQxgd,Payment,Credit Card,0
389,5Ege1rjWk4I8k4kKXA9WFK6BwLLbldiZMagDv,5.4,2018-05-26,Uber,oVBqkr7KvJcRbvbM4kZAHMKxgRmVqBTRyjKj9,Travel,Taxi,0

In [58]:
# добавим колонку в которой содержится только месяц и год из даты
for i in range(len(df_2)):
    df_2['year-month'][i] = df_2['date'][i][:7]

In [60]:
df_2.head(3)

,account_id,amount,date,name,transaction_id,category_1,category_2,category_3,year-month
0,lVKvzlNw69cW9j9NRDrkswg1obbBK5HZ8KJvW,500.0,2020-05-25,Tectra Inc,gV5nL83RoPcRwLwgdN8DH9wmv5avVEHg1oM7x,Food and Drink,Restaurants,0,2020-05
1,lVKvzlNw69cW9j9NRDrkswg1obbBK5HZ8KJvW,2078.5,2020-05-24,AUTOMATIC PAYMENT - THANK,WG5jed913Lt1d4d3b6MKIVR178x7BDtlER4Qr,Payment,0,0,2020-05
2,lVKvzlNw69cW9j9NRDrkswg1obbBK5HZ8KJvW,500.0,2020-05-24,KFC,E45mg16qJwFqjejpLG4wUmXq1o31yVFXlyE5K,Food and Drink,Restaurants,Fast Food,2020-05

In [130]:
# создадим отдельные таблицы для income and expense и отсортируем по месяцам
income = df_2[df_2['amount'] < 0].groupby(['year-month', 'category_1', 'category_2', 'category_3']).amount.agg([sum])
expense = df_2[df_2['amount'] > 0].groupby(['year-month', 'category_1', 'category_2', 'category_3']).amount.agg([sum])

In [118]:
# сумма денежных поток в каждой категории и в каждом месяце
income

                                                                    sum
year-month category_1 category_2                     category_3
2018-06    Transfer   Credit                         0            -4.22
           Travel     Airlines and Aviation Services 0          -500.00
2018-07    Transfer   Credit                         0            -4.22
           Travel     Airlines and Aviation Services 0          -500.00
2018-08    Transfer   Credit                         0            -4.22
           Travel     Airlines and Aviation Services 0          -500.00
2018-09    Transfer   Credit                         0            -4.22
           Travel     Airlines and Aviation Services 0          -500.00
2018-10    Transfer   Credit                         0            -4.22
           Travel     Airlines and Aviation Services 0          -500.00
2018-11    Transfer   Credit                         0            -4.22
           Travel     Airlines and Aviation Services 0          -500.00
2018-12    Transfer   Credit                         0            -4.22
           Travel     Airlines and Aviation Services 0          -500.00
2019-01    Transfer   Credit                         0            -4.22
           Travel     Airlines and Aviation Services 0          -500.00
2019-02    Transfer   Credit                         0            -4.22
           Travel     Airlines and Aviation Services 0          -500.00
2019-03    Transfer   Credit                         0            -4.22
           Travel     Airlines and Aviation Services 0          -500.00
2019-04    Transfer   Credit                         0            -4.22
           Travel     Airlines and Aviation Services 0          -500.00
2019-05    Transfer   Credit                         0            -4.22
           Travel     Airlines and Aviation Services 0          -500.00
2019-06    Transfer   Credit                         0            -4.22
           Travel     Airlines and Aviation Services 0          -500.00
2019-07    Transfer   Credit                         0            -4.22
           Travel     Airlines and Aviation Services 0          -500.00
2019-08    Transfer   Credit                         0            -4.22
           Travel     Airlines and Aviation Services 0          -500.00
2019-09    Transfer   Credit                         0            -4.22
           Travel     Airlines and Aviation Services 0          -500.00
2019-10    Transfer   Credit                         0            -4.22
           Travel     Airlines and Aviation Services 0          -500.00
2019-11    Transfer   Credit                         0            -4.22
           Travel     Airlines and Aviation Services 0          -500.00
2019-12    Transfer   Credit                         0            -4.22
           Travel     Airlines and Aviation Services 0          -500.00
2020-01    Transfer   Credit                         0            -4.22
           Travel     Airlines and Aviation Services 0          -500.00
2020-02    Transfer   Credit                         0            -4.22
           Travel     Airlines and Aviation Services 0          -500.00
2020-03    Transfer   Credit                         0            -4.22
           Travel     Airlines and Aviation Services 0          -500.00
2020-04    Transfer   Credit                         0            -4.22
           Travel     Airlines and Aviation Services 0          -500.00
2020-05    Transfer   Credit                         0            -4.22
           Travel     Airlines and Aviation Services 0          -500.00

In [152]:
# сумма денежных поток в каждой категории и в каждом месяце
expense

                                                                          sum
year-month category_1     category_2                     category_3
2018-05    Payment        Credit Card                    0              25.00
           Travel         Taxi                           0               5.40
2018-06    Food and Drink Restaurants                    0             589.40
                                                         Coffee Shop     4.33
                                                         Fast Food     512.00
           Payment        0                              0            2078.50
                          Credit Card                    0              25.00
           Recreation     Gyms and Fitness Centers       0              78.50
           Shops          Sporting Goods                 0             500.00
           Transfer       Debit                          0            5850.00
                          Deposit                        0            1000.00
           Travel         Airlines and Aviation Services 0             500.00
                          Taxi                           0              11.73
2018-07    Food and Drink Restaurants                    0             589.40
                                                         Coffee Shop     4.33
                                                         Fast Food     512.00
           Payment        0                              0            2078.50
                          Credit Card                    0              25.00
           Recreation     Gyms and Fitness Centers       0              78.50
           Shops          Sporting Goods                 0             500.00
           Transfer       Debit                          0            5850.00
                          Deposit                        0            1000.00
           Travel         Airlines and Aviation Services 0             500.00
                          Taxi                           0              11.73
2018-08    Food and Drink Restaurants                    0             589.40
                                                         Coffee Shop     4.33
                                                         Fast Food     512.00
           Payment        0                              0            2078.50
                          Credit Card                    0              25.00
           Recreation     Gyms and Fitness Centers       0              78.50
           Shops          Sporting Goods                 0             500.00
           Transfer       Debit                          0            5850.00
                          Deposit                        0            1000.00
           Travel         Airlines and Aviation Services 0             500.00
                          Taxi                           0              11.73
2018-09    Food and Drink Restaurants                    0             589.40
                                                         Coffee Shop     4.33
                                                         Fast Food     512.00
           Payment        0                              0            2078.50
                          Credit Card                    0              25.00
           Recreation     Gyms and Fitness Centers       0              78.50
           Shops          Sporting Goods                 0             500.00
           Transfer       Debit                          0            5850.00
                          Deposit                        0            1000.00
           Travel         Airlines and Aviation Services 0             500.00
                          Taxi                           0              11.73
2018-10    Food and Drink Restaurants                    0             589.40
                                                         Coffee Shop     4.33
                                                         Fast Food     512.00
           Payment        0                              0            2078.50
                          Credit Card                    0              25.00
           Recreation     Gyms and Fitness Centers       0              78.50
           Shops          Sporting Goods                 0             500.00
           Transfer       Debit                          0            5850.00
                          Deposit                        0            1000.00
           Travel         Airlines and Aviation Services 0             500.00
                          Taxi                           0              11.73
2018-11    Food and Drink Restaurants                    0             589.40
                                                         Coffee Shop     4.33
                                                         Fast Food     512.00
           Payment        0                              0            2078.50
                          Credit Card                    0              25.00
           Recreation     Gyms and Fitness Centers       0              78.50
           Shops          Sporting Goods                 0             500.00
           Transfer       Debit                          0            5850.00
                          Deposit                        0            1000.00
           Travel         Airlines and Aviation Services 0             500.00
                          Taxi                           0              11.73
2018-12    Food and Drink Restaurants                    0             589.40
                                                         Coffee Shop     4.33
                                                         Fast Food    1012.00
           Payment        0                              0            4157.00
                          Credit Card                    0              25.00
           Recreation     Gyms and Fitness Centers       0              78.50
           Shops          Sporting Goods                 0            1000.00
           Transfer       Debit                          0            5850.00
                          Deposit                        0            1000.00
           Travel         Airlines and Aviation Services 0             500.00
                          Taxi                           0              11.73
2019-01    Food and Drink Restaurants                    0            1089.40
                                                         Coffee Shop     4.33
                                                         Fast Food     512.00
           Payment        0                              0            2078.50
                          Credit Card                    0              25.00
           Recreation     Gyms and Fitness Centers       0              78.50
           Shops          Sporting Goods                 0             500.00
           Transfer       Debit                          0            5850.00
                          Deposit                        0            1000.00
           Travel         Airlines and Aviation Services 0             500.00
                          Taxi                           0              11.73
2019-02    Food and Drink Restaurants                    0              89.40
                                                         Coffee Shop     4.33
                                                         Fast Food      12.00
           Payment        Credit Card                    0              25.00
           Recreation     Gyms and Fitness Centers       0              78.50
           Transfer       Debit                          0            5850.00
                          Deposit                        0            1000.00
           Travel         Airlines and Aviation Services 0             500.00
                          Taxi                           0              11.73
2019-03    Food and Drink Restaurants                    0             589.40
                                                         Coffee Shop     4.33
                                                         Fast Food    1012.00
           Payment        0                              0            4157.00
                          Credit Card                    0              25.00
           Recreation     Gyms and Fitness Centers       0              78.50
           Shops          Sporting Goods                 0            1000.00
           Transfer       Debit                          0            5850.00
                          Deposit                        0            1000.00
           Travel         Airlines and Aviation Services 0             500.00
                          Taxi                           0              11.73
2019-04    Food and Drink Restaurants                    0             589.40
                                                         Coffee Shop     4.33
                                                         Fast Food     512.00
           Payment        0                              0            2078.50
                          Credit Card                    0              25.00
           Recreation     Gyms and Fitness Centers       0              78.50
           Shops          Sporting Goods                 0             500.00
           Transfer       Debit                          0            5850.00
                          Deposit                        0            1000.00
           Travel         Airlines and Aviation Services 0             500.00
                          Taxi                           0              11.73
2019-05    Food and Drink Restaurants                    0            1089.40
                                                         Coffee Shop     4.33
                                                         Fast Food     512.00
           Payment        0                              0            2078.50
                          Credit Card                    0              25.00
           Recreation     Gyms and Fitness Centers       0              78.50
           Shops          Sporting Goods                 0             500.00
           Transfer       Debit                          0            5850.00
                          Deposit                        0            1000.00
           Travel         Airlines and Aviation Services 0             500.00
                          Taxi                           0              11.73
2019-06    Food and Drink Restaurants                    0             589.40
                                                         Coffee Shop     4.33
                                                         Fast Food     512.00
           Payment        0                              0            2078.50
                          Credit Card                    0              25.00
           Recreation     Gyms and Fitness Centers       0              78.50
           Shops          Sporting Goods                 0             500.00
           Transfer       Debit                          0            5850.00
                          Deposit                        0            1000.00
           Travel         Airlines and Aviation Services 0             500.00
                          Taxi                           0              11.73
2019-07    Food and Drink Restaurants                    0             589.40
                                                         Coffee Shop     4.33
                                                         Fast Food     512.00
           Payment        0                              0            2078.50
                          Credit Card                    0              25.00
           Recreation     Gyms and Fitness Centers       0              78.50
           Shops          Sporting Goods                 0             500.00
           Transfer       Debit                          0            5850.00
                          Deposit                        0            1000.00
           Travel         Airlines and Aviation Services 0             500.00
                          Taxi                           0              11.73
2019-08    Food and Drink Restaurants                    0             589.40
                                                         Coffee Shop     4.33
                                                         Fast Food     512.00
           Payment        0                              0            2078.50
                          Credit Card                    0              25.00
           Recreation     Gyms and Fitness Centers       0              78.50
           Shops          Sporting Goods                 0             500.00
           Transfer       Debit                          0            5850.00
                          Deposit                        0            1000.00
           Travel         Airlines and Aviation Services 0             500.00
                          Taxi                           0              11.73
2019-09    Food and Drink Restaurants                    0             589.40
                                                         Coffee Shop     4.33
                                                         Fast Food     512.00
           Payment        0                              0            2078.50
                          Credit Card                    0              25.00
           Recreation     Gyms and Fitness Centers       0              78.50
           Shops          Sporting Goods                 0             500.00
           Transfer       Debit                          0            5850.00
                          Deposit                        0            1000.00
           Travel         Airlines and Aviation Services 0             500.00
                          Taxi                           0              11.73
2019-10    Food and Drink Restaurants                    0             589.40
                                                         Coffee Shop     4.33
                                                         Fast Food     512.00
           Payment        0                              0            2078.50
                          Credit Card                    0              25.00
           Recreation     Gyms and Fitness Centers       0              78.50
           Shops          Sporting Goods                 0             500.00
           Transfer       Debit                          0            5850.00
                          Deposit                        0            1000.00
           Travel         Airlines and Aviation Services 0             500.00
                          Taxi                           0              18.06
2019-11    Food and Drink Restaurants                    0             589.40
                                                         Coffee Shop     4.33
                                                         Fast Food     512.00
           Payment        0                              0            2078.50
                          Credit Card                    0              25.00
           Recreation     Gyms and Fitness Centers       0              78.50
           Shops          Sporting Goods                 0             500.00
           Transfer       Debit                          0            5850.00
                          Deposit                        0            1000.00
           Travel         Airlines and Aviation Services 0             500.00
                          Taxi                           0              11.73
2019-12    Food and Drink Restaurants                    0             589.40
                                                         Coffee Shop     4.33
                                                         Fast Food     512.00
           Payment        0                              0            2078.50
                          Credit Card                    0              25.00
           Recreation     Gyms and Fitness Centers       0              78.50
           Shops          Sporting Goods                 0             500.00
           Transfer       Debit                          0            5850.00
                          Deposit                        0            1000.00
           Travel         Airlines and Aviation Services 0             500.00
                          Taxi                           0              11.73
2020-01    Food and Drink Restaurants                    0             589.40
                                                         Coffee Shop     4.33
                                                         Fast Food     512.00
           Payment        0                              0            2078.50
                          Credit Card                    0              25.00
           Recreation     Gyms and Fitness Centers       0              78.50
           Shops          Sporting Goods                 0             500.00
           Transfer       Debit                          0            5850.00
                          Deposit                        0            1000.00
           Travel         Airlines and Aviation Services 0            1000.00
                          Taxi                           0              11.73
2020-02    Food and Drink Restaurants                    0             589.40
                                                         Coffee Shop     4.33
                                                         Fast Food     512.00
           Payment        0                              0            2078.50
                          Credit Card                    0              25.00
           Recreation     Gyms and Fitness Centers       0              78.50
           Shops          Sporting Goods                 0             500.00
           Transfer       Debit                          0            5850.00
                          Deposit                        0            1000.00
           Travel         Taxi                           0              11.73
2020-03    Food and Drink Restaurants                    0             589.40
                                                         Coffee Shop     4.33
                                                         Fast Food     512.00
           Payment        0                              0            2078.50
                          Credit Card                    0              25.00
           Recreation     Gyms and Fitness Centers       0              78.50
           Shops          Sporting Goods                 0             500.00
           Transfer       Debit                          0            5850.00
                          Deposit                        0            1000.00
           Travel         Airlines and Aviation Services 0            1000.00
                          Taxi                           0              11.73
2020-04    Food and Drink Restaurants                    0             589.40
                                                         Coffee Shop     4.33
                                                         Fast Food     512.00
           Payment        0                              0            2078.50
                          Credit Card                    0              25.00
           Recreation     Gyms and Fitness Centers       0              78.50
           Shops          Sporting Goods                 0             500.00
           Transfer       Debit                          0            5850.00
                          Deposit                        0            1000.00
           Travel         Airlines and Aviation Services 0             500.00
                          Taxi                           0              11.73
2020-05    Food and Drink Restaurants                    0             589.40
                                                         Coffee Shop     4.33

In [142]:
# преобразуем для записи в google spreadsheets
expense_no_index = expense.reset_index() 
income_no_index = income.reset_index()

In [143]:
# создадим spreadsheets для обработанных данных
in_ = gc.create('income')

# предоставим доступ
in_.share('dddiiirrr3@gmail.com', perm_type='user', role='writer')

# запишем данные в spreadsheets
list_1 = in_.sheet1
list_1.update([income_no_index.columns.values.tolist()] + income_no_index.values.tolist())


# создадим spreadsheets для обработанных данных
out_ = gc.create('expense')

# предоставим доступ
out_.share('dddiiirrr3@gmail.com', perm_type='user', role='writer')

# запишем данные в spreadsheets
list_1 = out_.sheet1
list_1.update([expense_no_index.columns.values.tolist()] + expense_no_index.values.tolist())

{'spreadsheetId': '1Xc-G7_qJfurDVgY2g9fTqYq4c7yTUeU5aFblI0N21q8',
 'updatedRange': 'Sheet1!A1:E263',
 'updatedRows': 263,
 'updatedColumns': 5,
 'updatedCells': 1315}

In [150]:
# сумма денежных поток каждый месяц без учета категорий
expense_no_index.groupby(['year-month'])['sum'].agg([sum])

                 sum
year-month
2018-05        30.40
2018-06     11149.46
2018-07     11149.46
2018-08     11149.46
2018-09     11149.46
2018-10     11149.46
2018-11     11149.46
2018-12     14227.96
2019-01     11649.46
2019-02      7570.96
2019-03     14227.96
2019-04     11149.46
2019-05     11649.46
2019-06     11149.46
2019-07     11149.46
2019-08     11149.46
2019-09     11149.46
2019-10     11155.79
2019-11     11149.46
2019-12     11149.46
2020-01     11649.46
2020-02     10649.46
2020-03     11649.46
2020-04     11149.46
2020-05     10643.13

In [151]:
# сумма денежных поток каждый месяц без учета категорий
income_no_index.groupby(['year-month'])['sum'].agg([sum])

               sum
year-month
2018-06    -504.22
2018-07    -504.22
2018-08    -504.22
2018-09    -504.22
2018-10    -504.22
2018-11    -504.22
2018-12    -504.22
2019-01    -504.22
2019-02    -504.22
2019-03    -504.22
2019-04    -504.22
2019-05    -504.22
2019-06    -504.22
2019-07    -504.22
2019-08    -504.22
2019-09    -504.22
2019-10    -504.22
2019-11    -504.22
2019-12    -504.22
2020-01    -504.22
2020-02    -504.22
2020-03    -504.22
2020-04    -504.22
2020-05    -504.22